version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./testvault:/app/testvault